---
title: "Deaths from suicide in young people, aged 11-25 years"
output: pdf_document
date: "2024-11-21"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load packages 

```{r load-packages}
library(tidyverse)

```

## Title and introduction 



## Data section 

## Read in data 

```{r read-data}
Suicide_data <- read.csv("~/Documents/Trends_ScotPHO_data_extract_2024-10-21.csv")

Suicide_data <- Suicide_data %>%
  mutate(year_start = substr(trend_axis, 1, 4))
```

## Prepare data 

```{r inspect_data}
glimpse(Suicide_data)
```
## Select trend_axis and measure 

```{r select_trend_axis_and_measure}
Deaths_from_suicide_in_young_people_aged_11_to_25_years <- Suicide_data %>%
  select(`trend_axis`,`measure`) %>%
  rename( `Frequency` = `trend_axis`,
          `Crude rate per 100000 population` = `measure`)
head(Deaths_from_suicide_in_young_people_aged_11_to_25_years)

```

## Remove missing values 
```{r missing-values}
Deaths_from_suicide_in_young_people_aged_11_to_25_years$`5-year period` %>% unique()
Deaths_from_suicide_in_young_people_aged_11_to_25_years$`Crude rate per 100,000 population` %>% table()
Deaths_from_suicide_in_young_people_aged_11_to_25_years %>% summary()
```
## Check that data is tidy

```{r tidy-data}
Suidicde_data <- Suicide_data %>% 
  mutate(year_start = substr(trend_axis, 1, 4))

```

## Plot graph 

```{r plot-graph}

#histogram 
Suicide_data %>%
  ggplot(aes(x = `measure`)) +
  geom_histogram(bins = 17) +
  labs( 
    title = "Distribution of Crude Suicide Rates", 
    x = "Crude rate per 100000 Population", 
    y = "Frequency"
  ) + 
  theme_minimal()
```

```{r plot_graph_two}
Suicide_data %>%
  ggplot(aes(x = year_start, y = measure)) +
  geom_col(fill = "yellow", colour = "black") +
  labs(
    title = "Crude Suicide Rates by Year Start",
    x = "Year Start",
    y = "Crude Rate per 100,000 Population"
  ) +
  theme_minimal()

```



## Graph type 3 

```{r trend_line}
Suicide_data %>%
  ggplot(aes(x = as.numeric(year_start), y = measure)) +  
  geom_col(fill = "yellow", colour = "black") +  
  geom_smooth(method = "lm", se = TRUE, colour = "blue", size = 1) + 
  labs(
    title = "Crude Suicide Rates by Year Start with Trend Line",
    x = "Year Start",
    y = "Crude Rate per 100,000 Population"
  ) +
  theme_minimal()
```

```{r Moving_trend_line}
Suicide_data %>%
  ggplot(aes(x = as.numeric(year_start), y = measure)) +  
  geom_col(fill = "yellow", colour = "black") +  
  geom_smooth(method = "lm", formula = y ~ poly(x, 4), se = TRUE, colour = "blue", size = 1) +  
  labs(
    title = "Crude Suicide Rates by Year Start with Polynomial Trend Line",
    x = "Year Start",
    y = "Crude Rate per 100,000 Population"
  ) +
  theme_minimal()
```



















